pull_request_rules:
- name: automatic rebase for dependencies
  conditions:
  - status-success=security-audit
  - status-success=check
  - status-success=version
  - status-success=test (macos-latest)
  - status-success=test (ubuntu-latest)
  - status-success=specdown (ubuntu-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-...
  - status-success=specdown (macos-latest, https://github.com/specdown/specdown/releases/download/v0.41.0/specdown-x...
  - status-success=lints
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    merge:
      strict: smart+fasttrack
      method: merge

