pull_request_rules:
- name: automatic rebase for dependencies
  conditions:
  - status-success=security-audit
  - status-success=check
  - status-success=version
  - status-success=test (macos-latest, echo nothing-to-install)
  - status-success=test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
    libxcb-xfixes0-dev)
  - status-success=lints
  - base=main
  - author~=^dependabot(|-preview)\[bot\]$
  actions:
    merge:
      strict: smart+fasttrack
      method: merge

