[package]
name = "ellipsis"
version = "0.6.19"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"
license = "CC0-1.0"
repository = "https://github.com/PurpleBooth/ellipsis"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "dotfiles" ]
description = "Manage dotfiles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
clap = "3.0.0-beta.5"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.8.21"
indoc = "1.0.3"
tempfile = "3.2.0"
regex = "1.5.2"
anyhow = "1.0.45"
