[package]
name = "ellipsis"
version = "0.1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"
license = "CC0-1.0"
repository = "https://github.com/PurpleBooth/ellipsis"
categories = [ "development-tools", "command-line-utilities" ]
keywords = [ "dotfiles" ]
description = "Manage dotfiles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
clap = "3.0.0-beta.2"
